server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tunnelurl?serverTimezone=UTC
    username: root
    password: ''

logging:
  level:
    root: error

